config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root :to => "pixoatics#home"
  get "service", to: "pixoatics#service", as: :"services"
  get "on-demand-developers", to: "pixoatics#onDemand", as: :"onDemandDeveloper"
  post "/on-demand-form", to: "pixoatics#demandForm", as: :"on_demand_form"
  post "on-contact-us-form", to: "pixoatics#contactUsForm", as: :"on_contact_us_form"
  get "react-native-development", to: "pixoatics#reactdevelopment", as: :"reactdevelopment"
  get "react-js-development", to: "pixoatics#jsdevelopment", as: :"jsdevelopment"
  get "ui-ux-development", to: "pixoatics#UI", as: :"ui-ux-development"
  get "qa-services", to: "pixoatics#QA", as: :"qa-development"
  get "rordeveloper", to: "pixoatics#rordeveloper"
  get "aboutUs", to: "pixoatics#aboutUs", as: :"aboutUs"
  get "career", to: "pixoatics#career", as: :"career"
  get "contactUs", to: "pixoatics#contactUs", as: :"contactUs"
  post "/apply_form", to: "pixoatics#apply_form"
end

app/controllers/pixoatics_controller.rb
class PixoaticsController < ApplicationController
  def home
  end

  def service
  end

  def onDemand
  end
  
  def demandForm
      @model_name = OnDemand::Form.new(model_name_params)
      respond_to do |format|
        if @model_name.valid?
          if ExampleMailer.with(resource: @model_name).resource_email.deliver_now
            format.json { render json: { success: true } }
          else
            format.json { render json: { success: false, errors: @model_name.errors.full_messages } }
          end
        else
          format.json { render json: { success: false, errors: @model_name.errors.full_messages } }
        end
      end
  end          
  
  def reactdevelopment
      @model_name = OnDemand::Form.new
  end   
  
  def rordeveloper
  end

  def aboutUs
  end

  def QA
  end

  def UI
  end

  def career
      @jobopening_obj = JobOpening.where(is_active: true)
      @apply_obj = Applyform.new
  end

  def jsdevelopment
  end

  def contactUs
  end

  def contactUsForm
    @model_name = Contact.new(contact_params)
      respond_to do |format|
        if @model_name.valid?
          if ExampleMailer.with(resource: @model_name).contact_us_email.deliver_now
            format.json { render json: { success: true } }
          else
            format.json { render json: { success: false, errors: @model_name.errors.full_messages } }
          end
        else
          format.json { render json: { success: false, errors: @model_name.errors.full_messages } }
        end
      end
  end

  def apply_form
    @apply_obj = Applyform.new(apply_form_params)
      respond_to do |format|
        if @apply_obj.valid?
          if ExampleMailer.with(resource: @apply_obj).career_email.deliver_now
            format.json { render json: { success: true }}
          else
            format.json { render json: { success: false, errors: @apply_obj.errors.full_messages }}
          end
        else
          format.json { render json: { success: false, errors: @apply_obj.errors.full_messages }}
        end
      end 
  end

  private

  def model_name_params
  # if params[:on_demand_form].present?
  #   params.require(:on_demand_form).permit(:full_name, :email, :country, :skype, :technologies, :resources, :message, :phone, :country_code)
  # else
  #   params.permit(:full_name, :email, :country, :skype, :technologies, :resources, :message, :phone, :country_code) 
  # end
  params.permit(:full_name, :email, :country, :skype, :technologies, :resources, :message, :phone, :country_code)
  
  end

  def contact_params
    params.permit(:name, :email, :country, :skype, :message, :attachment)
  end

  def apply_form_params
    params.require(:applyform).permit(:full_name, :email_address, :contact_number, :position, :experience, :current_ctc, :notice_period, :resume, :skill, :message, :pixoatic_terms)
  end
end

app/helpers/pixoatics_helper.rb
module PixoaticsHelper
end

app/views/pixoatics/career/_apply_form.html.erb
  <section class="">
  <div class="container pb-5 h-100">
    <div class="row justify-content-center align-items-center">
      <h2 class="apply-text text-center mb-3sssss">Applying For</h2>      
      <%= form_with model: @apply_obj, url: apply_form_path, id: "applyform", local: false do |form| %>

        <div class ="mb-2" id="apply-form-div">
          <%= render "layouts/share/errors", object: @apply_obj %>
        </div>

        <div class="row">
          <div class="col-md-6 mb-4">
            <div class="form-outline">
              <%= form.text_field :full_name, placeholder:"Full Name*",  class:"form-control form-control-lg" %>
              
            </div>
          </div>

          <div class="col-md-6 mb-4"> 
            <div class="form-outline">
              <%= form.email_field :email_address, placeholder:"Email Address*", class:"form-control form-control-lg"%>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-md-6 mb-4">
            <div class="form-outline">
              <%= form.text_field :contact_number, placeholder:"Contact Number*",  class:"form-control form-control-lg" %>
            </div>
          </div>

          <div class="col-md-6 mb-4"> 
            <div class="form-outline">
              <%= form.select :position, options_for_select(Applyform::POSITION),{ prompt: "Position"}, placeholder:"Position*", class:"form-select form-select-lg" %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-md-6 mb-4">
            <div class="form-outline">
              <%= form.select :experience, options_for_select(Applyform::EXPERIENCE),{ prompt: "Experience"}, { class: "form-select form-select-lg" } %>
            </div>
          </div>

          <div class="col-md-6 mb-4"> 
            <div class="form-outline">
              <%= form.text_field :current_ctc, placeholder:"Current CTC*",  class:"form-control form-control-lg" %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-md-6 mb-4">
            <div class="form-outline">
              <%= form.select :notice_period, options_for_select(Applyform::NOTICE_PERIOD),{ prompt: "Notice Period"}, placeholder:"Notice Period*", class:"form-select form-select-lg" %>
            </div>
          </div>

          <div class="col-md-6 mb-4"> 
            <div class="form-outline">
              <%= form.file_field :resume, placeholder:"Attach Resume*", class:"form-control form-control-lg"%>
            </div>
          </div>
        </div>

        <div class="col-md-12 mb-4 pl-0">
          <div class="form-outline">
            <%= form.text_field :skill, placeholder:"Describe Your Skills*", class:"form-control form-control-lg" %>
          </div>
        </div>

        <div class="col-md-12 mb-4 pl-0">
          <div class="form-outline">
            <%= form.text_area :message, placeholder:"Message*", class:"form-control form-control-lg" %>
          </div>
        </div>

        <div class="form-check d-flex justify-content-start ml-3 mb-4 pb-3 mt-5">
          <%= form.check_box :pixoatic_terms, id:"termscheckbox", class:"form-check-input me-3 career-form-checkbox" %>
          <%= form.label :pixoatic_terms, " I agree to the Terms and Conditions of Pixoatic.",  class:"text-secondary" %>
        </div>

        <div class="d-flex justify-content-center mt-4">
          <%= form.submit "Submit", id: "applysubmitbtn",:disabled => true, class:"apply-submit-btn btn btn-primary text-white btn-block btn-lg gradient-custom-4 rounded-pill w-100" %>
       
        </div> 
      <%end%>
    </div>
  </div>
</section>

<script>
  document.addEventListener("DOMContentLoaded", function () {
    var resetModalErrors = document.querySelectorAll("#reset-modal-errors");
    resetModalErrors.forEach(element => {
      element.addEventListener("click", function (event) {
          var requestQuoteDiv = document.querySelector('#apply-form-div');
          var errorContainer = requestQuoteDiv.querySelector('#error-container');
          errorContainer.classList.add('d-none');
       })
    });
    const termscheckbox = document.getElementById("termscheckbox");
    const applysubmitButton = document.getElementById("applysubmitbtn");
    const applyform = document.getElementById("applyform");
    
    termscheckbox.addEventListener("change", function () {
      applysubmitButton.disabled = !termscheckbox.checked;
    });

    applysubmitButton.addEventListener("click", function (event) {
      event.preventDefault();
      const formData = new FormData(applyform );
      
      fetch(applyform.action, {
      method: "POST",
      body: formData,
      headers: {
        "X-CSRF-Token": document.querySelector('meta[name="csrf-token"]').content,
      },
      })
      .then((response) => response.json())
        .then((data) => {
         
          if (data.success) {  
            var requestQuoteDiv = document.querySelector('#apply-form-div');
            var errorContainer = requestQuoteDiv.querySelector('#error-container');
            errorContainer.classList.add('d-none');
            alert("Thank you for your submission! We will review your message.");
            applyform.reset();
            applysubmitButton.disabled = true;
          
          } else {
            var requestQuoteDiv = document.querySelector('#apply-form-div');
            var errorContainer = requestQuoteDiv.querySelector('#error-container');
            errorContainer.classList.remove('d-none');
            var errors = data.errors.join("\n");
            requestQuoteDiv.querySelector('#error-list').innerText = errors;
          }
        })
      .catch((error) => {
        alert("An error occurred: " + error.message);
        
      });
      
    });
});

</script>

app/views/pixoatics/career/_career-banner.html.erb
<section>
    <div class="group1 container-fluid">
        <div class = "heading">
            <h1 class="bannerheading">Career In Our Company</h1>
        </div>

        <div class = "paragraph">
            <p class = "text-center">We are proud of giving growth opportunities to the emerging talent of the IT industry.</p>
        </div>
    </div>
</section>

app/views/pixoatics/career/_career-benefits.html.erb
<section class="careerbenifits removextrapad">
    <div class="career-benefits px-pd-5">
        <div class="benefits-heading pt-5">
            <h1 class="mainheadingeffects">Benefits of working with Pixoatic Solutions</h1>
            <p class="pt-2">One of the Best places to Work</p>
        </div>
        
        <div class="row main mt-2">
            <div class="col-sm-12 col-md-4 col-lg-4 col-xl-4 mb-2">
                <div class="card h-100">
                    <div class="card-body  boxsec">
                        <div class="">
                            
                            <h1 class="js-text1">Equal Opportunity</h1>
                        </div>
                        <p class="career-banner-text">We respect and value our every employee, we give them ample support for growth and pay attention to employee feedback.</p>
                    </div>
                </div>
            </div>
    
            <div class="col-sm-12 col-md-4 col-lg-4 col-xl-4 mb-2">
                <div class="card h-100">
                    <div class="card-body  boxsec">
                        <div class="">
                            
                            <h1 class="js-text1">Learning & Development</h1>
                        </div>
                        <p class="career-banner-text">Well defined technical and non-technical training sessions help to enhance their skills and be a better professional.</p>
                    </div>
                </div>
            </div>

            <div class="col-sm-12 col-md-4 col-lg-4 col-xl-4 mb-2">
                <div class="card h-100">
                    <div class="card-body  boxsec">
                        <div class="">
                        
                            <h1 class="js-text1">Favorable Work Environment</h1>
                        </div>
                        <p class="career-banner-text">We are provided with all necessary equipment, amenities, and conference rooms to facilitate smooth work.</p>
                    </div>
                </div>
            </div>
   
            <div class="col-sm-12 col-md-4 col-lg-4 col-xl-4 mt-2">
                <div class="card h-100">
                    <div class="card-body  boxsec ">
                        <div class="">
                        
                            <h1 class="js-text1">Leaders Support</h1>
                        </div>
                        <p class="career-banner-text">Timely guidance, feedback, and constructive evaluation to improve and develop skills.</p>
                    </div>
                </div>
            </div>

            <div class="col-sm-12 col-md-4 col-lg-4 col-xl-4 mt-2">
                <div class="card h-100">
                    <div class="card-body boxsec ">
                        <div class="">
                        
                            <h1 class="js-text1">Transparent Evaluation</h1>
                        </div>
                        <p class="career-banner-text">Well defined KRA/KPI's and 180 Degree evaluation for a fair assessment and salary hikes.</p>
                    </div>
                </div>
            </div>

            <div class="col-sm-12 col-md-4 col-lg-4 col-xl-4 mt-2">
                <div class="card h-100">
                    <div class="card-body  boxsec  ">
                        <div class="">
                        
                            <h1 class="js-text1">Strong Work Ethics and Transparency</h1>
                        </div>
                        <p class="career-banner-text">Integrity and work ethics are absolutely paramount at Athmin, it helps to serve our clients the best and ensure a transparent work environment.</p>
                    </div>
                </div>
            </div>
        </div>  
    
    </div>
</section>

app/views/pixoatics/career/_career-img.html.erb
<section>
    <div class="career-img d-flex flex-row justify-content-center">
        <div class="row ">
            <div class="d-sm-inline-flex flex-row ">
                <div class="d-sm-inline-flex flex-row">
                    <%= image_tag("officeimg1.jpg", class: "", alt: "...") %>
                </div>
                <div class="d-sm-inline-flex flex-column " >
                    <%= image_tag("officeimg2.jpg", class: "", alt: "...") %>
                    <div class="d-sm-inline-flex flex-row" >
                        <%= image_tag("officeimg7.jpg", class: "", alt: "...") %>
                        <%= image_tag("officeimg6.jpg", class: "", alt: "...") %>
                    </div>
                </div>
                <div class="d-sm-inline-flex flex-column">
                    <%= image_tag("officeimg5.jpg", class: "", alt: "...") %>
                    <%= image_tag("officeimg3.jpg", class: "", alt: "...") %>
                </div>
                <div class="d-sm-inline-flex flex-row " >
                    <%= image_tag("officeimg4.jpg", class: "img-fluid rounded mx-auto", alt: "...") %>
                </div>
            </div>
        </div>
    </div>

</section>
 
   

app/views/pixoatics/career/_clients.html.erb
<section class="logos mt-xs-1">
    <div class="" style="background: #F5F5FA;">
        <div class="row space6">
            <div class="py-5">
                <div class="logos main mt-0  d-flex flex-wrap justify-content-sm-center  justify-content-lg-evenly flex-row">
                    <%= image_tag("circle1.png", class: "img-fluid", alt: "circle") %>
                    <%= image_tag("codelab1.png", class: "img-fluid", alt: "codelab") %>
                    <%= image_tag("ideaa1.png", class: "img-fluid", alt: "idea") %>
                    <%= image_tag("hexa1.png", class: "img-fluid", alt: "hexa") %>
                    <%= image_tag("muzica1.png", class: "img-fluid", alt: "muzica") %>
                    <%= image_tag("lightal1.png", class: "img-fluid", alt: "lightai") %>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/pixoatics/career/_it-careers-banner.html.erb
<section class="pixoaticcareer removextrapad main">
    <div class="it-careers-banner container-fluid">
        <div class="row ">
            <div class="career-banner-heading">
                <h1 class="mainheadingeffects">Work with Pixoatic on promising IT careers</h1>
            </div>
        
            <div class="col-sm-12 col-md-6 col-lg-6 col-12">
            <div class="">
                <p class="career-banner-text">We are technology engineering, fast-growing, and a dynamic amusing company, we make technology roadblocks smoother by offering a multitude of custom software development services and solutions that help businesses to proceed easily with the latest technology disruptions.</p>
            </div>
            </div>
        
            <div class="col-sm-12 col-md-6 col-lg-6 col-12">
            <div class="career-banner-description">
                <p class="">At Pixoatic Solutions, we care for our employees and our clients, they are our most salient assets. We embrace clan organisational culture where every individual gets an equal chance for growth, exposure, and nurturing. We value our team and give a work-life balance and make their career growth and worth.</p>
            </div>
            </div>
        </div>
        </div>
</section>

app/views/pixoatics/career/_join-us.html.erb
<%= content_for :script do %>
  <%= javascript_include_tag "career.js" %>
<%end%>
<section class="careerbenifits join-us removextrapad">

   <div class="modal fade bd-example-modal-lg" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
            <div class="modal-header" style="border:none!important;">
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body p-0">
                <!-- Form -->
                <%= render "pixoatics/career/apply_form" %>             
            </div>
            </div>
        </div>
    </div>


    <div class=" px-pd-5">
        <div class="benefits-heading">
            <h1 class="mainheadingeffects">Join us</h1>
            <p class="">Current Openings</p>
        </div>
        <% if @jobopening_obj.nil? || @jobopening_obj.empty? %>
            <div class="row main benefits-headingcontent mt-2">
                <p class="text-center">We don't currently have any open vacancies</p>
            </div>
        <% else %>
            <% @jobopening_obj.each do |job_obj|%>
                <div class="row main benefits-headingcontent mt-2">
                    <div class="col-sm-12 col-md-12 col-lg-12 col-xl-12">
                        <h1 class="texteffects js-text1"><%= job_obj.title%></h1>
                    </div>
                    <div class="d-lg-inline-flex justify-content-between">
                        <div class="" style="margin-top: 12px;">
                            <div class="form-check-inline">
                                <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1" value="option1" />
                                <label class="form-check-label ms-1" for="inlineRadio1"><%= job_obj.experience_level %></label>
                            </div>
                            <div class=" form-check-inline ">
                                <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio2" value="option2" />
                                <label class="form-check-label ms-1" for="inlineRadio2"><%= job_obj.location %></label>
                            </div>

                            <div class=" form-check-inline ">
                                <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio3" value="option3" />
                                <label class="form-check-label ms-1" for="inlineRadio3"><%= job_obj.employment_type%></label>
                            </div>
                        </div>
                        <div class="btnmarginresp">
                            <button class=" btn btn-primary rounded-pill btnhover" data-bs-toggle="modal" data-bs-target="#exampleModal" id="reset-modal-errors" >Apply&nbsp; <i class="fa fa-arrow-right-long"></i></button>
                        </div>
                    </div>
                    <div class="mt-4">
                        <p><%= job_obj.one_line_description %></p>
                    </div>

                    <div class="read-more ">
                        <div class="">
                            <div class="btn2-text skill mt-5 hidden" >
                                <div><%= job_obj.brief_description.html_safe %></div>
                            </div>
                            <a id="btn2" class="btn2 " role="button" style="color: #222F9C;font-weight: 600;text-decoration: none;font-size: 20px;" aria-pressed="true">Read More</a>
                        
                        </div>
                    </div>
                    <div><hr></div>
                </div>
            <%end%>
        <% end %>
    </div>
</section>