config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root :to => "pixoatics#home"
  get "service", to: "pixoatics#service", as: :"services"
  get "on-demand-developers", to: "pixoatics#onDemand", as: :"onDemandDeveloper"
  post "/on-demand-form", to: "pixoatics#demandForm", as: :"on_demand_form"
  post "on-contact-us-form", to: "pixoatics#contactUsForm", as: :"on_contact_us_form"
  get "react-native-development", to: "pixoatics#reactdevelopment", as: :"reactdevelopment"
  get "react-js-development", to: "pixoatics#jsdevelopment", as: :"jsdevelopment"
  get "ui-ux-development", to: "pixoatics#UI", as: :"ui-ux-development"
  get "qa-services", to: "pixoatics#QA", as: :"qa-development"
  get "rordeveloper", to: "pixoatics#rordeveloper"
  get "aboutUs", to: "pixoatics#aboutUs", as: :"aboutUs"
  get "career", to: "pixoatics#career", as: :"career"
  get "contactUs", to: "pixoatics#contactUs", as: :"contactUs"
  post "/apply_form", to: "pixoatics#apply_form"
end

app/controllers/pixoatics_controller.rb
class PixoaticsController < ApplicationController
  def home
  end

  def service
  end

  def onDemand
  end
  
  def demandForm
      @model_name = OnDemand::Form.new(model_name_params)
      respond_to do |format|
        if @model_name.valid?
          if ExampleMailer.with(resource: @model_name).resource_email.deliver_now
            format.json { render json: { success: true } }
          else
            format.json { render json: { success: false, errors: @model_name.errors.full_messages } }
          end
        else
          format.json { render json: { success: false, errors: @model_name.errors.full_messages } }
        end
      end
  end          
  
  def reactdevelopment
      @model_name = OnDemand::Form.new
  end   
  
  def rordeveloper
  end

  def aboutUs
  end

  def QA
  end

  def UI
  end

  def career
      @jobopening_obj = JobOpening.where(is_active: true)
      @apply_obj = Applyform.new
  end

  def jsdevelopment
  end

  def contactUs
  end

  def contactUsForm
    @model_name = Contact.new(contact_params)
      respond_to do |format|
        if @model_name.valid?
          if ExampleMailer.with(resource: @model_name).contact_us_email.deliver_now
            format.json { render json: { success: true } }
          else
            format.json { render json: { success: false, errors: @model_name.errors.full_messages } }
          end
        else
          format.json { render json: { success: false, errors: @model_name.errors.full_messages } }
        end
      end
  end

  def apply_form
    @apply_obj = Applyform.new(apply_form_params)
      respond_to do |format|
        if @apply_obj.valid?
          if ExampleMailer.with(resource: @apply_obj).career_email.deliver_now
            format.json { render json: { success: true }}
          else
            format.json { render json: { success: false, errors: @apply_obj.errors.full_messages }}
          end
        else
          format.json { render json: { success: false, errors: @apply_obj.errors.full_messages }}
        end
      end 
  end

  private

  def model_name_params
  # if params[:on_demand_form].present?
  #   params.require(:on_demand_form).permit(:full_name, :email, :country, :skype, :technologies, :resources, :message, :phone, :country_code)
  # else
  #   params.permit(:full_name, :email, :country, :skype, :technologies, :resources, :message, :phone, :country_code) 
  # end
  params.permit(:full_name, :email, :country, :skype, :technologies, :resources, :message, :phone, :country_code)
  
  end

  def contact_params
    params.permit(:name, :email, :country, :skype, :message, :attachment)
  end

  def apply_form_params
    params.require(:applyform).permit(:full_name, :email_address, :contact_number, :position, :experience, :current_ctc, :notice_period, :resume, :skill, :message, :pixoatic_terms)
  end
end

app/helpers/pixoatics_helper.rb
module PixoaticsHelper
end

app/views/pixoatics/QA.html.erb
<%= stylesheet_link_tag "animation.css", media: "all" %>
<%= render "header" %>
<%= render "pixoatics/QA/banner" %>
<%= render "pixoatics/QA/build_production"%>
<%= render "pixoatics/QA/banner_img"%>
<%= render "pixoatics/QA/design" %>
<%= render "form", banner_title: "Manual Software?", technology: "QA" %>
<%= render "footer" %>

app/views/pixoatics/UI.html.erb
<%= stylesheet_link_tag "animation.css", media: "all" %>
<%= stylesheet_link_tag "style.css", media: "all" %>
<%= render "header" %>
<%= render "pixoatics/UI/banner" %>
<%= render "pixoatics/UI/web_app" %>
<%= render "pixoatics/UI/web" %>
<%= render "pixoatics/UI/workflow" %>
<%= render "pixoatics/UI/design" %>
<%= render "pixoatics/home/ourwork" %>
<%= render "form", banner_title: "UI/UX Designer?", technology: "UI" %>
<%= render "footer" %>

app/views/pixoatics/_footer.html.erb
<footer class="footer">
    <div class="main mt-0" style="margin-top:0px !important;">
            <div class="row px-3 pt-5" >
                <div class="col-12 col-sm-12 col-md-6 col-lg-3 col-xl-3">
                    <div class="footerlogo">
                        
                        <a class="logo" href="<%= root_path %>">
                            <%= image_tag('Logo.png', class: 'img-fluid', alt: 'logo') %>
                        </a>
                     </div>
                     <p class="wedo_des pt-4">We help businesses grow by services that matter</p>
                     <div class="footerIcons mt-5">
                        
                        <ul class="list-unstyled">
                            <li class="wedo_des "><i class="fa fa-regular fa-envelope fa-lg"></i><a href="mailto:Support@pixoatic.com" class="ps-2" target="blank">Support@pixoatic.com</a></li>
                            <li class="wedo_des"><i class="fa fa-brands fa-skype fa-xl"></i><a href="https://join.skype.com/invite/xPYNPI9sJXho" class="ps-2" target="blank">Pixoatic Solutions</a></li>
                        </ul>
                        <%= image_tag('iso_certified.png', class: 'img-fluid', alt: 'iso_certified') %>
                    </div>
                </div>
                <div class="col-12 col-sm-12 col-md-6 col-lg-3 col-xl-3">
                    <div>
                        
                        <h3 class="wedo_title">Company</h3>
                        
                        <ul class="list-group">
                            <li class="list-group-item wedo_des"><a href="<%= aboutUs_path %>">About Us</a></li>
                            <li class="list-group-item wedo_des"><a href="<%= career_path %>">Careers</a></li>
                        </ul>
                        
                        <h4 class="wedo_title mt-4">Dedicated Hiring</h4>
                        
                    <p class="wedo_des"><a href="<%= onDemandDeveloper_path %>">Looking to hire for long-term or full-time assignments?</a></p>
                    </div>
                </div>
                <div class="col-12 col-sm-12 col-md-6 col-lg-3 col-xl-3">
                    <div>
                        
                        <h3 class="wedo_title">Services</h3>
                        
                        <ul class="list-group">
                            <li class="list-group-item wedo_des"><a href="<%= ui_ux_development_path %>">UI/UX design and development</a></li>
                            <li class="list-group-item wedo_des"><a href="<%= rordeveloper_path %>">ROR Development</a></li>
                            <li class="list-group-item wedo_des"><a href="<%= reactdevelopment_path %>">React Native Development</a></li>
                            <li class="list-group-item wedo_des"><a href="<%= jsdevelopment_path %>">React JS Development</a></li>
                            <li class="list-group-item wedo_des"><a href="<%= qa_development_path %>">Quality Assurance Services</a></li>                            
                        </ul>
                        
                    </div>
                </div>
                <div class="col-12 col-sm-12 col-md-6 col-lg-3 col-xl-3">
                    <div>
                        
                        <h4 class="wedo_title">Contact</h4>
                        <h5 class="wedo_title">
                            <%= image_tag('india.png', class: 'img-fluid', alt: 'india') %>
                            India
                        </h5>
                        <p class="wedo_des">131, Shubh Sampada, Nipania, Indore, Madhya Pradesh 453771</p><br>
                        <p class="wedo_des mt8">E-237AA, Industrial AreaPhase 8B, Mohali 160071</p>
                    </div>
                </div>
            </div>
    </div>
    <div class=" bottom-para" style="background-color: #fff;">
        <div class="row px-1 pt-4 main">
            <div class="col-xs-12 col-md-3 text-xs-center">
                <p>Copyright@ 2023 All right reserved</p>
            </div>
            <div class="col-md-3"></div>
            <div class="col-md-3"></div>
            <div class="col-xs-12 col-md-3 text-xs-center">
                <div class="row">
                    <ul class="list-inline">
                        <li class=" list-inline-item wedo_des"><a href="https://www.behance.net/Pixoaticsolutions" target="blank"><i class="fa fa-brands fa-behance fa-xl"></i></a></li>
                        <li class="list-inline-item wedo_des"><a href="https://www.instagram.com/pixoatic/" target="blank"><i class="fa fa-brands fa-instagram fa-xl"></i></a></li>
                        <li class="list-inline-item wedo_des"><a href="https://www.linkedin.com/company/pixoatic-solutions/" target="blank"><i class="fa fa-brands fa-linkedin fa-xl"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
<footer>

app/views/pixoatics/_form.html.erb
<section class="formsec">   
    <div class="formbox" >
    <figure class="mb-0" style="position: relative;">
    <figcaption class="box" style="background-image: url('<%= asset_path('reactformbg.jpg') %>');">       
        <div class="row ">
          <div class=" ">
              <div class="main row mt-2">
                <div class="col-sm-12 col-md-12 col-lg-12 col-xl-12 p-0">
                  <p class="text1  pt-5 fw-light mb-1">Looking To Hire</p>
                  <h6 class="text1  pb-3"><%= banner_title %></h6>
                </div>
              </div>              
              <div class="main row mt-4">
                <div class="col-sm-12 col-md-7 col-lg-7 col-xl-7 p-0">
                    <div class ="mb-2" id="on-demand-form-errors">
                      <%= render "layouts/share/errors", object: @apply_obj %>
                    </div>
                  <%= form_tag(on_demand_form_path, method: :post, remote: true, id: "myForm", class: "row g-3") do %>
                    
                    <div class="col-sm-12 col-md-6 col-lg-6 col-xl-6 mt-sm-1 mt-md-5">
                      <%= text_field_tag 'full_name', nil, class: 'form-control full-name-input', placeholder: 'Full Name*', required: true %>
                      <span class="error-message" id="full_name-error"></span>
                    </div>
                    <div class="col-sm-12 col-md-6 col-lg-6 col-xl-6 mt-sm-1 mt-md-5">
                      <%= text_field_tag 'email', nil, class: 'form-control email-input', placeholder: 'Email*' %>
                      <span class="error-message" id="email-error"></span>
                    </div>
                    <div class="col-sm-12 col-md-6 col-lg-6 col-xl-6 mt-sm-1 mt-md-5">
                      <%= text_field_tag 'country', nil, class: 'form-control', placeholder: 'Country*' %>
                      <span class="error-message" id="country-error"></span>
                    </div>
                    <div class="col-sm-12 col-md-6 col-lg-6 col-xl-6 mt-sm-1 mt-md-5">
                      <%= text_field_tag 'skype', nil, class: 'form-control', placeholder: 'Skype' %>
                    </div>
                    <% if technology == 'onDemand' %>
                      <div class="col-sm-12 col-md-6 col-lg-6 col-xl-6 mt-sm-1 mt-md-5">
                        <%= select_tag 'technologies', options_for_select(OnDemand::Form::TECHNOLOGIES), class: 'form-select', prompt: "Technologies*" %>
                        <span class="error-message" id="technologies-error"></span>
                      </div>
                      <div class="col-sm-12 col-md-6 col-lg-6 col-xl-6 mt-sm-1 mt-md-5">
                        <%= select_tag 'resources', options_for_select(OnDemand::Form::RESOURCES), class: 'form-select', prompt: "Resources Required*" %>
                        <span class="error-message" id="resources-error"></span>
                      </div>
                    <% elsif technology == 'ROR' %>
                      <%= hidden_field_tag 'technologies', 'Ruby on rails' %>
                      <%= hidden_field_tag 'resources', 'specify in message' %>
                    <% elsif technology == 'ReactJs' %>
                      <%= hidden_field_tag 'technologies', 'React Js' %>
                      <%= hidden_field_tag 'resources', 'specify in message' %>
                    <% elsif technology == 'QA' %>
                      <%= hidden_field_tag 'technologies', 'QA / Tester' %>
                      <%= hidden_field_tag 'resources', 'specify in message' %>
                    <% elsif technology == 'UI' %>
                      <%= hidden_field_tag 'technologies', 'UI/UX Designer' %>
                      <%= hidden_field_tag 'resources', 'specify in message' %>
                    <% else %>
                      <%= hidden_field_tag 'technologies', 'React Native' %>
                      <%= hidden_field_tag 'resources', 'specify in message' %>
                    <% end %>
                    <div class="col-sm-offset-2 col-sm-12 col-md-12 col-lg-12 col-xl-12 mt-sm-1 mt-md-5">
                      <%= text_area_tag 'message', nil, class: 'form-control', rows: 1, placeholder: 'Message*' %>
                    </div>
                    <div class="col-sm-12 col-md-12 col-lg-3 col-xl-3">
                      <a class="btn btn-primary rounded-pill btnhover mt-3", id="submitFormBtn">Submit <i class="fa fa-arrow-right-long"></i></a>
                    </div>
                  <% end %>                
                </div>
              </div>
            </div> 
        </div>  
        <figcaption>   
    </figure>
        </div>
</section>
<style>
  section.formsec .box{
    height: inherit;
    padding-bottom: 39px;
    background-size: cover;
    background-repeat: no-repeat;
    background-position: center;
    position: relative;
    }

  section.formsec  form   .form-select {
    color: #6F7377;
    background-color: transparent; border-bottom: 1px solid #CED4DA;
    border-top: 1px solid transparent!important;
    border-left: 1px solid transparent!important;
    border-right: 1px solid transparent!important;padding: 0px;
  }
  section.formsec  form   .form-select {
        box-shadow:none!important;
  }
</style>

<script>
  document.addEventListener("DOMContentLoaded", function () {
    const submitButton = document.getElementById("submitFormBtn");
    const form = document.getElementById("myForm");
    submitButton.addEventListener("click", function (event) {
      event.preventDefault();
      const formData = new FormData(form);
      fetch(form.action, {
        method: "POST",
        body: formData,
        headers: {
          "X-CSRF-Token": document.querySelector('meta[name="csrf-token"]').content,
        },
      })
        .then((response) => response.json())
        .then((data) => {
          if (data.success) {
            alert("Thank you for your submission! We will review your message.");
            form.reset();
            var requestQuoteDiv = document.querySelector('#on-demand-form-errors');
            var errorContainer = requestQuoteDiv.querySelector('#error-container');
            errorContainer.classList.add('d-none');
          } else {
            var requestQuoteDiv = document.querySelector('#on-demand-form-errors');
            var errorContainer = requestQuoteDiv.querySelector('#error-container');
            errorContainer.classList.remove('d-none');
            var errors = data.errors.join("\n");
            requestQuoteDiv.querySelector('#error-list').innerText = errors;
          }
        })
        .catch((error) => {
          alert("An error occurred: " + error.message);
        });
    });
  });
</script>

app/views/pixoatics/_header.html.erb
<header class="header">
    <div class="modal fade bd-example-modal-lg" id="requestquote" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header" style="border:none!important;">
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body p-0">
                    <!-- Form -->
                    <%= render "pixoatics/request_quote_form" %>
                            
                </div>
            </div>
        </div>
    </div>

    <nav class="navbar navbar-expand-lg navbar-light mt-2">
        <div class="container-fluid">
            <a class="me-5 pe-5" href="<%= root_path %>">
                <%= image_tag('Logo.png', class: 'img-fluid', alt: 'logo') %>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mx-auto mb-2 mb-lg-0">
                    <li class="nav-item p-1">
                        <a 
                            class="nav-link <%= 'active' if current_page?(:controller => 'pixoatics', :action => 'home')%>"
                            href="<%= root_path %>">
                            Home
                        </a>
                    </li>

                    <li class="nav-item p-1">
                        <a 
                            class="nav-link <%= 'active' if current_page?(:controller => 'pixoatics', :action => 'aboutUs')%>"
                            href="<%= aboutUs_path %>">
                            About Us
                        </a>
                    </li>


                    <li class="nav-item p-1" >
                        <a class="nav-link <%= 'active' if current_page?(:controller => 'pixoatics', :action => 'service') || current_page?(:controller => 'pixoatics', :action => 'rordeveloper') || current_page?(:controller => 'pixoatics', :action => 'jsdevelopment') || current_page?(:controller => 'pixoatics', :action => 'reactdevelopment') || current_page?(:controller => 'pixoatics', :action => 'QA') || current_page?(:controller => 'pixoatics', :action => 'UI') %>" href="<%= services_path %>">Service</a>
                    </li> 
                    <li class="nav-item dropdown p-1">
                        <a 
                            class="nav-link <%= 'active' if current_page?(:controller => 'pixoatics', :action => 'onDemand')%>"
                            href="<%= onDemandDeveloper_path %>" tabindex="-1" aria-disabled="true">On-Demand Developers</a>
                    </li>
                    <li class="nav-item p-1">
                        <a class="nav-link <%= 'active' if current_page?(:controller => 'pixoatics', :action => 'career')%>" href="<%= career_path %>" tabindex="-1" aria-disabled="true">Careers</a>
                    </li>
                    <li class="nav-item p-1">
                        <a class="nav-link <%= 'active' if current_page?(:controller => 'pixoatics', :action => 'contactUs')%>" href="<%= contactUs_path %>">Contact Us</a>
                    </li>
                    
                </ul>
                <button type="button" class="btn btn-outline-primary rounded-pill ms-auto expertbtn" data-bs-toggle="modal" data-bs-target="#requestquote" id="reset-1-modal-errors">Request Quote</button>
            </div>
        </div>
    </nav>
</header>

app/views/pixoatics/_request_quote_form.html.erb
<section class="requesformmodal">
  <div class="container pb-5 h-100">
    <div class="row justify-content-center align-items-center">
      <h2 class="apply-text text-center mb-4">Request Quote</h2>  

      <%= form_with model: @model_name, url: on_demand_form_path,  id:"requestQuoteForm" do |form| %>

        <div class ="mb-2" id="request-quote-div" >
          <%= render "layouts/share/errors", object: @model_name %>
        </div>

        <div class="row">
          <div class="col-md-6 mb-4">
            <div class="form-outline">
              <%= form.text_field :full_name, placeholder:"Full Name*",  class:"form-control form-control-lg" %>
              
            </div>
          </div>

          <div class="col-md-6 mb-4"> 
            <div class="form-outline">
              <%= form.email_field :email, placeholder:"Email Address*", class:"form-control form-control-lg"%>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-md-6 mb-4">
            <div class="form-outline">
              <%= form.text_field :country, placeholder:"Country*",  class:"form-control form-control-lg" %>
            </div>
          </div>

          <div class="col-md-6 mb-4">
            <div class="form-outline selectPhoneCode d-flex justify-content-arround">
              <select name="country_code" class="formSelect" style="background: #e0e0e09c;">
              <% ISO3166::Country.countries.each do |country| %>
                <option value="+<%= country.country_code%>" <%= 'selected' if country.alpha2 == 'IN'%>>   
                  <%= "+#{country.country_code}"%>
                </option>
              <%end%>
              <%= form.text_field :phone, placeholder:"9234567891",  class:"form-control form-control-lg" %>  
            </select>
            </div>
          </div>
        </div>

         <div class="row">
          <div class="col-md-12 mb-4">
            <div class="form-outline">
              <%= form.text_field :skype, placeholder:"Skype",  class:"form-control form-control-lg" %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-md-6 mb-4">
            <div class="form-outline">
              <%= form.select :technologies, options_for_select(OnDemand::Form::TECHNOLOGIES),{ prompt: "Technologies*"}, { class: "form-select form-select-lg" } %>
            </div>
          </div>

           <div class="col-md-6 mb-4">
            <div class="form-outline">
              <%= form.select :resources, options_for_select(OnDemand::Form::RESOURCES),{ prompt: "Resources Required*"}, { class: "form-select form-select-lg" } %>
            </div>
          </div>
        </div>


        <div class="col-md-12 mb-4 pl-0">
          <div class="form-outline">
            <%= form.text_area :message, placeholder:"Message*", class:"form-control form-control-lg" %>
          </div>
        </div>

        <div class="d-flex justify-content-center mt-4">
          <%= form.submit "Submit" , id:"requestQuoteSubmitBtn", class:"apply-submit-btn btn btn-primary text-white btn-block btn-lg gradient-custom-4 rounded-pill w-100"  %>
        </div> 
      <%end%>
    </div>
  </div>
</section>

<style>
 .form-select-lg, .form-control{color: #787b7e;
     background-color:  #e0e0e09c;padding:15px;
    }
   h2 {
    font-family: 'Poppins';
    font-style: normal;
    font-weight: 700;
    font-size: 36px;
    line-height: 45px;
    color: #30303C;
    }
  
  .selectPhoneCode .formSelect, .selectPhoneCode .formSelect:focus, .selectPhoneCode .formSelect:focus-visible {
    width: 25%;
    padding: 7px;
    border: 1px solid #ced4da;
    outline: none;border-radius: 4px;
    }
    

    @media  (min-width:768px) and (max-width:991px){
      .selectPhoneCode .formSelect, .selectPhoneCode .formSelect:focus, .selectPhoneCode .formSelect:focus-visible {
      width: 60%;}
    }

    @media  (max-width:327px){
      .selectPhoneCode .formSelect{
         width: 60%;
      }
      
    } 
</style>

<script>
document.addEventListener("DOMContentLoaded", function () {
    var resetModalErrors = document.querySelectorAll("#reset-1-modal-errors");
    resetModalErrors.forEach(element => {
      element.addEventListener("click", function (event) {
        document.getElementById('error-container').classList.add('d-none')
       })
    });   
    const requestQuoteSubmitBtn = document.getElementById("requestQuoteSubmitBtn");
    const quoteform = document.getElementById("requestQuoteForm");    
    requestQuoteSubmitBtn.addEventListener("click", function (event) {
      event.preventDefault();
      const formData = new FormData(quoteform);
      
      fetch(quoteform.action, {
      method: "POST",
      body: formData,
      headers: {
        "X-CSRF-Token": document.querySelector('meta[name="csrf-token"]').content,
      },
      })
      .then((response) => response.json())
        .then((data) => {
          if (data.success) {  
            var requestQuoteDiv = document.querySelector('#request-quote-div');
            var errorContainer = requestQuoteDiv.querySelector('#error-container');
            errorContainer.classList.add('d-none');
            alert("Thank you for your submission! We will review your message.");
            quoteform.reset();
          
          } else {
            var requestQuoteDiv = document.querySelector('#request-quote-div');
            var errorContainer = requestQuoteDiv.querySelector('#error-container');
            errorContainer.classList.remove('d-none');
            var errors = data.errors.join("\n");
            requestQuoteDiv.querySelector("#error-list").innerText = errors;
          }
        })
      .catch((error) => {
        alert("An error occurred: " + error.message);
        
      });
      
    });
  });
</script>

app/views/pixoatics/aboutUs.html.erb
<%= stylesheet_link_tag "animation.css", media: "all" %>
<%= render "header" %>
<%= render "pixoatics/aboutUs/banner" %>
<%= render "pixoatics/aboutUs/about" %>
<%= render "pixoatics/aboutUs/value" %>
<%= render "pixoatics/aboutUs/talk" %>
<%= render "pixoatics/aboutUs/clients" %>
<%= render "footer" %>

app/views/pixoatics/career.html.erb
<%= stylesheet_link_tag "animation.css", media: "all" %>
<%= render "header" %>
<%= render "pixoatics/career/career-banner"%>
<%= render "pixoatics/career/it-careers-banner" %>
<%= render "pixoatics/career/career-benefits" %>
<%= render "pixoatics/career/career-img" %>
<%= render "pixoatics/career/join-us" %>
<%= render "pixoatics/career/clients" %>
<%= render "footer" %>

app/views/pixoatics/contactUs.html.erb
<%= stylesheet_link_tag "animation.css", media: "all" %>
<%= render "header" %>
<%= render "pixoatics/contactUs/banner" %>
<%= render "pixoatics/contactUs/goodTalk" %>
<%= render "pixoatics/contactUs/getTouch" %>
<%= render "pixoatics/contactUs/form" %>
<%= render "pixoatics/contactUs/location" %>
<%= render "footer" %>

app/views/pixoatics/home.html.erb
<%= stylesheet_link_tag "animation.css", media: "all" %>
<%= render "header" %>
<%= render "pixoatics/home/banner" %>
<%= render "pixoatics/home/clients" %>
<%= render "pixoatics/home/services" %>
<%= render "pixoatics/home/wedo" %>
<%= render "pixoatics/home/whywork" %>
<%= render "pixoatics/home/ourwork" %>
<%= render "footer" %>

app/views/pixoatics/jsdevelopment.html.erb
<%= stylesheet_link_tag "animation.css", media: "all" %>
<%= render "header" %>
<%= render "pixoatics/js-development/js-banner" %>
<%= render "pixoatics/js-development/js-service-banner"%>
<%= render "pixoatics/js-development/js-development-services"%> 
<%= render "pixoatics/js-development/js-web-development" %>
<%= render "form", banner_title: "React Js Developers?", technology: "ReactJs" %>
<%= render "pixoatics/js-development/js_question"%>
<%= render "footer" %>

app/views/pixoatics/reactdevelopment.html.erb
<%= stylesheet_link_tag "animation.css", media: "all" %>
<%= stylesheet_link_tag "style.css", media: "all" %>
<%= render "header" %>
<%= render "pixoatics/reactdeveloper/react_banner"%>
<%= render "pixoatics/reactdeveloper/react_native_banner"%>
<%= render "pixoatics/reactdeveloper/react_native_development_banner"%>
<%= render "pixoatics/reactdeveloper/react_native_hiring"%>
<%= render "pixoatics/reactdeveloper/react_native_process"%>
<%= render "form", banner_title: "React Native Developers?", technology: "ReactNative" %>
<%= render "pixoatics/reactdeveloper/react_question"%>
<%= render "footer" %>
<style>
    section.processsec #myGroup .midddlebox ul.first-text li a.nav-link:link, 
    section.processsec #myGroup .midddlebox ul.first-text li a.nav-link:active, 
    section.processsec #myGroup .midddlebox ul.first-text li a.nav-link:focus{color: #00dcdf!important;text-decoration: none;}

</style>

app/views/pixoatics/rordeveloper.html.erb
<%= stylesheet_link_tag "animation.css", media: "all" %>
<%= render "header" %>
<%= render "pixoatics/RORDeveloper/banner" %>
<%= render "pixoatics/RORDeveloper/pixoatic_solutions"%>
<%= render "pixoatics/RORDeveloper/Development_services"%>
<%= render "pixoatics/RORDeveloper/ror-project_or_idea"%>
<%= render "pixoatics/RORDeveloper/ror_development_process"%>
<%= render "form", banner_title: "Ruby on Rails Developers?", technology: "ROR" %>
<%= render "pixoatics/RORDeveloper/questions"%>
<%= render "footer" %>

app/views/pixoatics/service.html.erb
<%= stylesheet_link_tag "animation.css", media: "all" %>
<%= render "header" %>
<%= render "pixoatics/service/banner" %>
<%= render "pixoatics/service/clients" %>
<%= render "pixoatics/service/customservice" %>
<%= render "pixoatics/service/industryservice" %>
<%= render "pixoatics/service/technologies" %>
<%= render "pixoatics/service/ourwork" %>
<%= render "pixoatics/service/ourapproach" %>
<%= render "footer" %>